version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.api
      target: api-production
    command: yarn run start
    volumes:
      - ./backend:/srv/backend
      - backend_node_modules:/srv/backend/node_modules
    expose:
      - "4000"
      - "27017"
    ports:
      - "4000:4000"
      - "27017:27017"
    restart: on-failure
    networks:
      - gateway

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
      target: client-production
    command: yarn run start
    volumes:
      - ./client:/srv/client
      - client_node_modules:/srv/client/node_modules
    expose:
      - "3000"
      - "4000"
    ports:
      - "3000:3000"
    stdin_open: true
    restart: on-failure
    networks:
      - gateway


  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.nginx
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - gateway
    depends_on:
      - client
      - backend

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 4100:8025 # web ui
    depends_on:
      - client
      - backend
    networks:
      - gateway

networks:
  gateway: {}

volumes:
  client_node_modules:
  backend_node_modules:
